### ISSUE TITLE
Incorrect Buttons Displayed After Validation Errors

### ISSUE THREAD

**Issue by schluebbo** [imi-ms/MoPat#137]
#### **Description**
When a validation error occurs while editing a questionnaire (e.g., duplicate name), the **Duplicate buttons** (`duplicate`, `duplicateEditButton`) are displayed instead of the **Save buttons** (`save`, `saveEditButton`). 

#### **Expected Behavior**
- **Save buttons** should be displayed if the questionnaire is editable.
- **Duplicate buttons** should only appear if editing is not allowed.

**Comment by ywarnecke** [comment]
Merged with #140
